add_newline = false
format = "$hostname$character$directory"
right_format = "$git_branch$git_commit$git_state$git_metrics$git_status"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[hostname]
ssh_only = true
format = "[$hostname]($style)"
style = "fg:#ff8800"
# [cmd_duration]
# show_notifications = true
# min_time_to_notify = 2
# [package]
# disabled = true
